### ISSUE TITLE
Cannot load savefile!

### ISSUE THREAD

**Issue by TheRobotGamerRO** [durkhaz/MSCEditor#1]
That is what I was getting in v1.02 after changing the name because it had some weird squares inside it. Now, with v1.03, I get this:
Load Failure at Offset : 51554
Unexpected end of entry. Expected symbol: {
Btw the symbol is right at that offset when I check it with notepad++. Any help? I would love to use Satsuma report. Here is my save: 
[defaultES2File.txt](https://github.com/durkhaz/MSCEditor/files/817539/defaultES2File.txt)

**Comment by durkhaz** [comment]
[defaultES2File.txt](https://github.com/durkhaz/MSCEditor/files/858811/defaultES2File.txt)

I fixed your savefile! There was a bug in v1.02 that caused this. I'm sorry I didn't see this earlier, I was on vacation.

**Comment by TheRobotGamerRO** [comment]
I knew I should've update the save... That is the old one. But can you explain me how to fix the current one?
[defaultES2File.txt](https://github.com/durkhaz/MSCEditor/files/870649/defaultES2File.txt)
Sorry for this, I would love to know if I can fix the new one myself.

**Comment by durkhaz** [comment]
It's a bit hard to explain. But for this one I just copied the last part over.
[defaultES2File .txt](https://github.com/durkhaz/MSCEditor/files/870686/defaultES2File.txt)

**Comment by TheRobotGamerRO** [comment]
Thanks, I will test it soon.
