### ISSUE TITLE
Map feature open source?

### ISSUE THREAD

**Issue by fizzl** [durkhaz/MSCEditor#13]
Hi! 
I wanted to make some quality of life improvements, like autoloading the default file on open and maximizing windows.

I cloned the project and very soon realized I cannot compile it, due to missing map file. After also figuring out the map compiled in the binary is not a valid jpg, I looked into the map source. It seems that the map data is purposefully obfuscated and the deobfuscation code omitted.

Would it be possible to open source these parts also? Or is there a commercial stake with the software? Or copyright issue?

It's none of my business, if you don't want to open source these parts. Just asking because I would like to make some small improvements to it myself :)

**Comment by durkhaz** [comment]
Hi,
sorry for the late response, I don't check this account often. 
I chose to obfuscate the map file to make it harder for people to steal it and use it for their mods. Capturing the entire map wasn't an easy task at the time. 
I won't open source the obfuscation, but I can share the source image once I'm home. Maybe you could also download it off of here somehow: https://www.easyzoom.com/imageaccess/e3e3752de3e34d7294437d34e6ef02a0

**Comment by durkhaz** [comment]
There you go: https://drive.google.com/file/d/1mzYHU2Qy7a0qcdx3XkHOMs7hkW8ynk-M/
