### ISSUE TITLE
Load failure at Offset: -1 ifstream fail! when file is removed

### ISSUE THREAD

**Issue by Kattus** [durkhaz/MSCEditor#3]
I had edited a backup which I then renamed to be the "main" savefile, opening MSCEditor then goes in an endless loop of wanting to reload and then giving an error for both options.

as shown here
https://f.lewd.se/HOywMQ_2017-04-16_19-25-07.mp4

**Comment by durkhaz** [comment]
Thank you for your report, it was an easy fix with the info you provided!
