### ISSUE TITLE
[Suggestion] More values to Satsuma report.

### ISSUE THREAD

**Issue by Fredrik95** [durkhaz/MSCEditor#4]
There are a few values that are missing from the maintenance tab in the satsuma report.

oilpanoilcontamination, default value = ?
wheelfldamagevector, default value = 0,0,0
wheelfrdamagevector, default value = 0,0,0
wheelrldamagevector, default value = 0,0,0
wheelrrdamagevector, default value = 0,0,0

Items.txt:
oilfilterXdirt, default value = 1
batteryXcharge, default value = 145
batteryXdischarge, default value = 0.0003

Just wanted to see if you maybe could add them.

Thanks!
Regards,
Fredrik.

**Comment by durkhaz** [comment]
"oilpanoilcontamination" is already in the list under the entry "Oil condition", but I'll add the rest. Good find, cheers!
