### ISSUE TITLE
group entries in items.txt

### ISSUE THREAD

**Issue by Fredrik95** [durkhaz/MSCEditor#5]
When opening items.txt the list is very long, especially after playing for a long time.

So the list looks something like:

battery0charge
battery0consumed
battery0discharge
battery0installed
battery0oncharged
battery0transform
battery1charge
...

It would be better if the individual items be grouped together in the right entries window. Much like how the regular defaultES2File looks. So that the left list looks more like:

battery0
battery1
batteryid
beercase0
beercase1
....

And then each of those have all the entries relevant in the right window.
I don't know if that would be hard to implement, but it would definitely enhance the readability of the left list.

Hope I was clear enough :)

Thanks!

**Comment by durkhaz** [comment]
That's definitively doable. Good call!

**Comment by Fredrik95** [comment]
Great! Looking forward to it. My 150 kilju bottles are taking up a lot of space in the list :D
