### ISSUE TITLE
Cannot Load Savfile!!!

### ISSUE THREAD

**Issue by Lizzardude** [durkhaz/MSCEditor#6]
Ok so i am unable to load my savefile, when I try to it says: Offset: 63987 Unexpected end of entry. Expected symbol: {

[defaultES2File.txt](https://github.com/durkhaz/MSCEditor/files/2848451/defaultES2File.txt)

**Comment by durkhaz** [comment]
I took a look at the file, and it's really messed up, Did you edit the txt with a Text-editor at some point? If not, could you describe what you did for this to happen? Cheers
