### ISSUE TITLE
Could not write to app folder at path

### ISSUE THREAD

**Issue by ma-schulz** [durkhaz/MSCEditor#7]
When I start MSCEditor, I get an error

> Could not write to app folder at path:
> ""
> Please report this issue

I traced the issue to utils.cpp, ln 77 if the folder exists, otherwise ln 128.

I have Windows 1803, Build 17134.590 and I mapped my documents dir to another hard drive. 

When I hardcode another documents dir, the program runs just fine.

As I'm not very experienced in C++ I'm unable to solve the issue...

**Comment by durkhaz** [comment]
Hm, I can't seem to reproduce the issue on my end. I take it that `wszPath` is empty when this is called?
`SHGetKnownFolderPath(FOLDERID_Documents, KF_FLAG_DEFAULT, NULL, &wszPath);`

**Comment by catb0t** [comment]
You have write access to the location, right?

**Comment by durkhaz** [comment]
Could also be your AV blocking write access

**Comment by ma-schulz** [comment]
Hi,
you were right. Apparently it was some new windows feature which blocks apps for specific folders. Thank you for your time!
